name: PR Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Dependencies for Vulnerabilities
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical


  build-test:
    name: Build & Test
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      node_version: '20'
      run_tests: true

  pr-comment:
    name: PR Summary Comment
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Print PR summary
        run: |
          echo " PR checks passed for branch: ${{ github.head_ref }}"
          echo " Test result: ${{ needs.build-test.outputs.test_result }}"
          echo " Commit: ${{ github.sha }}"